# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://nguyenphi0205.github.io/
baseurl: /PhiNguyen/
title: Phi Nguyen
author: Phi Nguyen
description: Personal blog and resume
avatar: demo.jpg
email: nguyenphi0511@yahoo.com.vn
github: nguyenphi0205 # username
twitter: username
linkedin: phi-nguyen-96079413b/
stackoverflow: users/9642748/phi-nguyen   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
